<script setup lang="ts">
import { onMounted } from "vue";
import { useResource } from "../composables";
import { useQualityApi } from "../context";
import ConnectionBanner from "../components/ConnectionBanner.vue";
import PageHeader from "../components/PageHeader.vue";
import ResourceState from "../components/ResourceState.vue";
import ScoreGauge from "../components/ScoreGauge.vue";
const api = useQualityApi(); const resource = useResource(signal => api.releases(signal)); onMounted(() => resource.load());
</script>
<template><section class="page"><PageHeader title="Release comparison" subtitle="Compare quality signals between two tested releases" :updated-at="resource.lastUpdated.value" @refresh="resource.load(true)"/><ConnectionBanner :state="resource.state.value" :message="resource.error.value" @retry="resource.load()"/><ResourceState :state="resource.state.value" :message="resource.error.value" @retry="resource.load()"><template v-if="resource.data.value"><article class="release-hero panel"><div class="release-score"><ScoreGauge :score="resource.data.value.base.score" compact/><div><span>Previous release</span><h2>{{ resource.data.value.base.version }}</h2><p>{{ resource.data.value.base.date }}</p></div></div><div class="release-arrow">→</div><div class="release-score current"><ScoreGauge :score="resource.data.value.current.score" compact/><div><span>Current release</span><h2>{{ resource.data.value.current.version }}</h2><p>{{ resource.data.value.current.date }}</p></div></div></article><article class="panel table-panel"><div class="panel-heading"><span class="section-label">Metric changes</span><span class="muted">Compared with previous release</span></div><div class="responsive-table"><table><thead><tr><th>Metric</th><th>{{ resource.data.value.base.version }}</th><th>{{ resource.data.value.current.version }}</th><th>Change</th></tr></thead><tbody><tr v-for="metric in resource.data.value.metrics" :key="metric.label"><td data-label="Metric"><strong>{{ metric.label }}</strong></td><td :data-label="resource.data.value.base.version">{{ metric.base }}</td><td :data-label="resource.data.value.current.version">{{ metric.current }}</td><td data-label="Change"><span class="change-pill" :class="(metric.lowerIsBetter ? metric.change <= 0 : metric.change >= 0) ? 'positive' : 'negative'">{{ metric.change >= 0 ? '↑' : '↓' }} {{ Math.abs(metric.change) }}%</span></td></tr></tbody></table></div></article></template></ResourceState></section></template>
