<script setup lang="ts">
import { onMounted } from "vue";
import { useResource } from "../composables";
import { useQualityApi } from "../context";
import ConnectionBanner from "../components/ConnectionBanner.vue";
import PageHeader from "../components/PageHeader.vue";
import QualityIcon from "../components/QualityIcon.vue";
import ResourceState from "../components/ResourceState.vue";
import StatusBadge from "../components/StatusBadge.vue";
const api = useQualityApi(); const resource = useResource(signal => api.configuration(signal)); onMounted(() => resource.load());
</script>
<template><section class="page"><PageHeader title="Quality Center settings" subtitle="Read-only runtime configuration and feature status" :updated-at="resource.lastUpdated.value" @refresh="resource.load(true)"/><ConnectionBanner :state="resource.state.value" :message="resource.error.value" @retry="resource.load()"/><div class="safety-note"><QualityIcon name="lock" :size="22"/><div><strong>Configuration is managed server-side</strong><span>This page cannot reveal credentials or relax authorization, environment, or runner policies.</span></div></div><ResourceState :state="resource.state.value" :message="resource.error.value" @retry="resource.load()"><template v-if="resource.data.value"><div class="settings-grid"><article class="panel"><div class="panel-heading"><span class="section-label">Versioned policy</span></div><dl class="detail-list"><div><dt>Catalog version</dt><dd><code>{{ resource.data.value.catalogVersion }}</code></dd></div><div><dt>Policy version</dt><dd><code>{{ resource.data.value.policyVersion }}</code></dd></div></dl></article><article class="panel"><div class="panel-heading"><span class="section-label">Your capabilities</span></div><div class="capability-list"><div v-for="(value, key) in resource.data.value.capabilities" :key="key"><QualityIcon :name="value ? 'check' : 'lock'" :size="17"/><span>{{ String(key).replace(/([A-Z])/g, ' $1') }}</span><StatusBadge :status="value ? 'passed' : 'cancelled'" :label="value ? 'Allowed' : 'Unavailable'"/></div></div></article></div><article class="panel settings-section"><div class="panel-heading"><span class="section-label">Runtime adapters</span></div><div class="adapter-grid"><div v-for="adapter in resource.data.value.adapters" :key="adapter.name"><span class="large-icon"><QualityIcon name="settings" :size="24"/></span><span><strong>{{ adapter.name }}</strong><small>{{ adapter.value }}</small></span><StatusBadge :status="adapter.state === 'active' ? 'passed' : adapter.state === 'planned' ? 'queued' : 'cancelled'" :label="adapter.state"/></div></div></article><article class="panel settings-section"><div class="panel-heading"><span class="section-label">Features</span></div><div class="feature-list"><div v-for="feature in resource.data.value.features" :key="feature.name"><span><strong>{{ feature.name }}</strong><small>{{ feature.description }}</small></span><StatusBadge :status="feature.enabled ? 'passed' : 'cancelled'" :label="feature.enabled ? 'Enabled' : 'Disabled'"/></div></div></article></template></ResourceState></section></template>
